### PR TITLE
fix recommended permissions for munge key and race conditions for ser…

### PR DESCRIPTION
**Pull request by jjhidalgar**
I don't know if it is because I am using OSX instead of linux, but your script failed for me in two ways:
1. slurmctld was not running on controller (I don't know the reason but taking off -t command option make it work)
2. Munge key was not working so I restart the server software in the end.

So i provide this fork in case it helps someone.

### CODE REVIEW

**Comment by stevekm** [comment]
Thanks, I also set this up with OS X. I have found it to be very difficult to successfully script all the steps due to things like race conditions and lag in service starting, in general I do not consider it to be 100% scripted but instead a very hands-on setup guide. Its hard to tell if adding/removing steps will increase or decrease reproducibility, I will try to test these updates.

**Comment by jjhidalgar** [comment]
I agree, It was very helpful anyway!, I tried to fix the script just for fun, I don't really know why is it so hard to script, in the end restarting the services made the trick, but when doing it manually it wasn't necessary though.

**Comment by jjhidalgar** [comment]
I close it because with my solution I still need to reload the daemons after booting.

**Comment by stevekm** [comment]
hey check out the updates I just put into the Makefile, it seems to have fixed the issues on my end, maybe this will fix the issues you were having as well. I added some extra commands to the start commands. I think part of the issue is that when you pass ssh commands into the Vagrant VMs, the connection closes too fast before the commands can finish taking effect. Adding 'sleep' and other commands after seems to let them finish easier

**Pull request closed without merging**
